### ISSUE TITLE
Change user agent

### ISSUE THREAD

**Issue by UltraHQ** [TurfuGoldy/LoggerFucker#1]
Current user agent (python-requests/2.25.1) makes it easy to sort out, which IPs are real and which not.
A user agent like `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36` will be better

**Comment by TurfuGoldy** [comment]
Done ;)
